name: ngm-salam
version: '0.0.9'
# grade: devel
grade: stable
summary: Say Salam
description: |
    Just say Salam
    From a Python app

base: core22

# confinement: devmode
confinement: strict

parts:
    ngm-salam:
        plugin: python
        source: .

apps:
    salam:
        command: bin/salam
        # command: build/lib/ngm_salam/__main__.py
        plugs: [network, home]
